apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: calculator
  name: calculator-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - image: calculator:latest
        name: calculator
        imagePullPolicy: Never        
